#!/usr/bin/env python3
#
# Copyright (C) 2026 Hiroshi Miura <miurahr@linux.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""Generates a `CMakeUserPresets.json` describing every Qt kit found in an aqt output directory.

This file is written inside the Qt install location itself, not a project tree: it is meant to
be copied by hand into whichever project needs it (a common pattern when one Qt install is
shared across several projects/machines). Because nothing else should ever write into an aqt
output directory, aqt treats this file as its own generated artifact: every run rewrites it
from scratch, scanning the *entire* output directory so the file always reflects every kit
installed there, not just the kit(s) from the most recent install.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, List

_VERSION_DIR_RE = re.compile(r"^\d+(\.\d+){1,2}$")
_CMAKE_PRESETS_SCHEMA_VERSION = 6
_MIN_CMAKE = {"major": 3, "minor": 23, "patch": 0}

PRESETS_FILENAME = "CMakeUserPresets.json"


def _looks_like_qt_kit(kit_dir: Path) -> bool:
    if (kit_dir / "lib" / "cmake").is_dir():
        return True
    bin_dir = kit_dir / "bin"
    return bin_dir.is_dir() and any(bin_dir.glob("qmake*"))


def _find_kits(output_dir: Path) -> List[Path]:
    """Scans `output_dir` for `<version>/<arch>` directories that look like installed Qt kits."""
    if not output_dir.is_dir():
        return []
    kits = []
    for version_dir in sorted(p for p in output_dir.iterdir() if p.is_dir() and _VERSION_DIR_RE.match(p.name)):
        for arch_dir in sorted(p for p in version_dir.iterdir() if p.is_dir()):
            if _looks_like_qt_kit(arch_dir):
                kits.append(arch_dir)
    return kits


def _preset_for_kit(kit_dir: Path) -> Dict[str, Any]:
    version_name = kit_dir.parent.name
    arch_name = kit_dir.name
    name = f"qt-{version_name}-{arch_name}"

    cache_variables: Dict[str, str] = {"CMAKE_PREFIX_PATH": str(kit_dir.resolve())}
    for qt_major_dir in ("Qt6", "Qt5"):
        toolchain = kit_dir / "lib" / "cmake" / qt_major_dir / "qt.toolchain.cmake"
        if toolchain.is_file():
            cache_variables["CMAKE_TOOLCHAIN_FILE"] = str(toolchain.resolve())
            break

    return {
        "name": name,
        "displayName": f"Qt {version_name} ({arch_name})",
        "description": f"Generated by 'aqt install --generate-cmake-presets' for {kit_dir}",
        "binaryDir": "${sourceDir}/build/" + name,
        "cacheVariables": cache_variables,
    }


def generate_cmake_user_presets(output_dir: Path) -> Path:
    """(Re)writes `CMakeUserPresets.json` inside `output_dir`, one preset per Qt kit found there."""
    kits = _find_kits(output_dir)
    document = {
        "version": _CMAKE_PRESETS_SCHEMA_VERSION,
        "cmakeMinimumRequired": _MIN_CMAKE,
        "configurePresets": [_preset_for_kit(kit) for kit in kits],
    }
    preset_path = output_dir / PRESETS_FILENAME
    preset_path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    return preset_path
